  # Copyright (c) 2025, yasaisen.
  # All rights reserved.
  # 
  # last modified in 2505142257

model:
  reward_model:
    bert_name: "bert-base-chinese"
    prefix_length: 20
    PPO_mode: False
    tokenizer_max_length: 492

dataset:
  data_path: "dataset/GAD_2505091031RMv2_2505130038_human_eval.xlsx"
  split_ratio: 0.80

task:
  root_path: ""

  num_epoch: 100
  batch_size_train: 24
  batch_size_eval: 24
  
  learning_rate: 1e-3
  max_lr: 1e-3
  pct_start: 0.2
  weight_decay: 1e-4
  anneal_strategy: "cos"
  
  device: "cuda"
  output_path: "outputs"
