site_name: hardPrompt2softPrompt
site_description: a research prototype that converts a fixed hard prompt into a learnable soft prefix using reinforcement learning
site_url: https://github.com/yasaisen/hardPrompt2softPrompt

theme:
  name: material
  language: zh-TW
  # palette:
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     primary: indigo
  #     accent: indigo
  #     toggle:
  #       icon: material/brightness-7
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     primary: indigo
  #     accent: indigo
  #     toggle:
  #       icon: material/brightness-4
  #       name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.top
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md